package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/avhn/fortix/internal/profile"
	"github.com/avhn/fortix/internal/secrets"
)

// credentialVector is one entry of credential-targets.json, which internal/secrets owns.
type credentialVector struct {
	Name      string `json:"name"`
	ID        string `json:"id"`
	Host      string `json:"host"`
	Port      int    `json:"port"`
	Username  string `json:"username"`
	TupleJSON string `json:"tuple_json"`
	Target    string `json:"target"`
}

// checkCredentials recomputes every credential target with secrets.Key and the Go tuple
// encoding. The file itself is generated by the secrets package tests, so this module only
// verifies it and never rewrites it.
func checkCredentials(dir string) error {
	data, err := os.ReadFile(filepath.Join(dir, "credential-targets.json"))
	if err != nil {
		return err
	}
	var vectors []credentialVector
	if err := json.Unmarshal(data, &vectors); err != nil {
		return err
	}
	if len(vectors) == 0 {
		return fmt.Errorf("no credential vectors")
	}
	for _, v := range vectors {
		tuple, err := json.Marshal([]any{v.Host, v.Port, v.Username})
		if err != nil {
			return err
		}
		p := &profile.Profile{ID: v.ID, Gateway: profile.Gateway{Host: v.Host, Port: v.Port}, Username: v.Username}
		if string(tuple) != v.TupleJSON || "fortix:"+secrets.Key(p)+":password" != v.Target {
			return fmt.Errorf("credential vector %s drifted", v.Name)
		}
	}
	return nil
}
